# Generated by Django 5.0.1 on 2024-01-30 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yosh', models.PositiveIntegerField()),
                ('kurs', models.PositiveIntegerField()),
                ('s_raqam', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satrlavha', models.CharField(max_length=200)),
                ('sana', models.DateField()),
                ('malumot', models.TextField(null=True)),
                ('bajarildi', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumot.muallif')),
            ],
        ),
    ]
