# Generated by Django 5.0.1 on 2024-01-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malumot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muallif',
            old_name='s_raqam',
            new_name='student_raqam',
        ),
    ]
