# Generated by Django 5.0.1 on 2024-01-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malumot', '0002_rename_s_raqam_muallif_student_raqam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reja',
            old_name='satrlavha',
            new_name='satlavha',
        ),
    ]
