# Generated by Django 5.0.1 on 2024-01-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malumot', '0003_rename_satrlavha_reja_satlavha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reja',
            old_name='satlavha',
            new_name='sarlavha',
        ),
    ]
